[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = ["lib", "dependencies", "node_modules"]
solc_version = "0.8.28"
# 启用优化器
optimizer = true
# 优化器的运行次数
optimizer_runs = 9999

[dependencies]
forge-std = "1.9.4"
solmate = "6.8.0"
"@openzeppelin-contracts" = "5.2.0-rc.0"

[profile.config.ftm]
single_line_statement_blocks = 'multi'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
