[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = ["lib", "dependencies", "node_modules"]
solc_version = "0.8.28"
# 启用优化器
optimizer = true
via_ir = true
# 优化器的运行次数
optimizer_runs = 1000000

[dependencies]
forge-std = "1.9.4"
solmate = "6.8.0"
"@openzeppelin-contracts" = "5.2.0-rc.0"
"@uniswap-v2-core" = "1.0.1"

[profile.config.ftm]
single_line_statement_blocks = 'multi'

[fuzz]
seed = '0x1314520'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-optionsruns = 256
show_logs = true
